### ISSUE TITLE
satpy 0.17 does not work with pyresample 1.11

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#918]
**Describe the bug**

According to satpy`s version requirements file, satpy 0.17 needs pyresample 1.11 or higher.  But it does not work with pyresample 1.11, see below for details.

**To Reproduce**

```bash

conda create -n py37_sandbox python=3.7
conda activate py37_sandbox
conda install pyresample=1.11 satpy=0.17
python -c "from satpy import Scene"
```

**Expected behavior**

I expect this to complete without any error message.

**Actual results**

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/satpy/__init__.py", line 53, in <module>
    from satpy.writers import available_writers  # noqa
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/satpy/writers/__init__.py", line 41, in <module>
    from satpy.resample import get_area_def
  File "/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/satpy/resample.py", line 148, in <module>
    from pyresample import bucket
ImportError: cannot import name 'bucket' from 'pyresample' (/media/nas/x21324/miniconda3/envs/py37_sandbox/lib/python3.7/site-packages/pyresample/__init__.py)
```

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.17.0
 - PyResample Version: 1.11.2

**Comment by djhoese** [comment]
@pnuu This is the issue I brought up on Satpy. @gerritholl Thanks for bringing this up. We should try for a quick patch release that either has a try/except around this import (my preference) or force the pyresample minimum version.

**Comment by gerritholl** [comment]
The minimum version would be 1.13.0, released 2019-09-13?

**Comment by pnuu** [comment]
Yes. Both bucket and bilinear interpolation methods won't work with anything older than 1.13.0.
